# Generated by Django 4.2.7 on 2023-12-29 23:00

import EtudiantApp.data_models.memoire
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CSSAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_login', models.BooleanField(default=True)),
                ('telephone', models.CharField(max_length=255)),
                ('date_nais', models.DateField()),
                ('civilite', models.CharField(choices=[('MARIÉ', 'MARIÉ'), ('VEUF(VE)', 'VEUF(VE)'), ('Célibataire', 'Célibataire')], default='Célibataire', max_length=20)),
                ('genre', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], default='Homme', max_length=20)),
                ('imagesprofiles', models.ImageField(default='images/r.jpeg', max_length=500, upload_to='images/')),
                ('role', models.CharField(choices=[('CSS', 'CSS'), ('Directeur', 'Directeur'), ('Etudiant', 'Etudiant')], max_length=20)),
                ('matricule', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('Identification', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('cycle', models.CharField(choices=[('licence', 'LICENCE'), ('dut', 'DUT')], default='licence', max_length=20)),
                ('filiere', models.CharField(choices=[('informatique', 'INFORMATIQUE'), ('administration', 'ADMINISTRATION')], default='informatique', max_length=20)),
                ('niveaux', models.CharField(choices=[('licence1', 'LICENCE1'), ('licence2', 'LICENCE2'), ('licence3', 'LICENCE3'), ('dut1', 'DUT1'), ('dut2', 'DUT2')], default='licence1', max_length=20)),
                ('statut', models.CharField(choices=[('En Frequentation', 'En Fréquentation'), ('Ancien etudiant', 'Ancien étudiant')], default='En Frequentation', max_length=20)),
                ('mois_debut_annee_academique', models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=9)),
                ('annee_academique', models.CharField(choices=[('2023 - 2024', '2023 - 2024'), ('2024 - 2025', '2024 - 2025'), ('2025 - 2026', '2025 - 2026'), ('2026 - 2027', '2026 - 2027'), ('2027 - 2028', '2027 - 2028'), ('2028 - 2029', '2028 - 2029'), ('2029 - 2030', '2029 - 2030')], default='2023 - 2024', max_length=19)),
                ('annee_frequentation_fin', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('est_lue', models.BooleanField(default=False)),
                ('is_accept', models.BooleanField(default=False)),
                ('is_refused', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('mem', models.CharField(max_length=20)),
                ('destinataire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notifications_destinataire', to='EtudiantApp.etudiant')),
                ('destinataire_css', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notifications_destinataire_css', to='CSSAPP.css')),
                ('expediteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notifications_expediteur', to='EtudiantApp.etudiant')),
                ('expediteur_css', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notifications_expediteur_css', to='CSSAPP.css')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Memoire',
            fields=[
                ('Id_mem', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('date_poste', models.DateField(default=datetime.date.today)),
                ('matricule_identification_binome', models.CharField(blank=True, max_length=20, null=True)),
                ('document', models.FileField(max_length=500, upload_to='memoires', validators=[EtudiantApp.data_models.memoire.validate_pdf_extension])),
                ('binome_notification_envoyee', models.BooleanField(default=False)),
                ('is_pubied', models.BooleanField(default=False)),
                ('identite', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='auteur_principal', to='EtudiantApp.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_nais', models.DateField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=20)),
                ('objet_demande', models.CharField(choices=[('attestation_frequentation', 'Attestation de fréquentation'), ('attestation_reussite', 'Attestation de réussite'), ('bulletin', 'Bulletin')], max_length=50)),
                ('session_dut', models.CharField(blank=True, choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4')], max_length=2, null=True)),
                ('session_lic', models.CharField(blank=True, choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4'), ('S5', 'S5'), ('S6', 'S6')], max_length=2, null=True)),
                ('annee_academique', models.CharField(choices=[('2023 - 2024', '2023 - 2024'), ('2024 - 2025', '2024 - 2025'), ('2025 - 2026', '2025 - 2026'), ('2026 - 2027', '2026 - 2027'), ('2027 - 2028', '2027 - 2028'), ('2028 - 2029', '2028 - 2029'), ('2029 - 2030', '2029 - 2030')], max_length=50)),
                ('mois', models.CharField(choices=[('janvier', 'Janvier'), ('février', 'Février'), ('mars', 'Mars'), ('avril', 'Avril'), ('mai', 'Mai'), ('juin', 'Juin'), ('juillet', 'Juillet'), ('août', 'Août'), ('septembre', 'Septembre'), ('octobre', 'Octobre'), ('novembre', 'Novembre'), ('décembre', 'Décembre')], max_length=50)),
                ('filiere', models.CharField(max_length=12)),
                ('cycle', models.CharField(max_length=12)),
                ('niveau', models.CharField(max_length=12)),
                ('date_poste_demande', models.DateField(default=datetime.date.today)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EtudiantApp.etudiant')),
                ('identite_receptioniste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CSSAPP.css')),
            ],
        ),
    ]
