# Generated by Django 4.2.6 on 2023-10-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('date_nais', models.DateField()),
                ('civilite', models.CharField(choices=[('marié', 'Marié'), ('veuf(ve)', 'Veuf(ve)'), ('célibataire', 'Célibataire')], max_length=20)),
            ],
        ),
    ]
