# Generated by Django 4.2.7 on 2023-11-07 21:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CSSAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('date_nais', models.DateField()),
                ('civilite', models.CharField(choices=[('marié', 'MARIE'), ('veuf(ve)', 'VEUF(VE)'), ('célibataire', 'CELIBATAIRE')], default='Célibataire', max_length=20)),
                ('cycle', models.CharField(choices=[('licence', 'LICENCE'), ('dut', 'DUT')], default='licence', max_length=20)),
                ('filiere', models.CharField(choices=[('informatique', 'INFORMATIQUE'), ('administration', 'ADMINISTRATION')], default='informatique', max_length=20)),
                ('niveaux', models.CharField(choices=[('licence1', 'LICENCE1'), ('licence2', 'LICENCE2'), ('licence3', 'LICENCE3'), ('dut1', 'DUT1'), ('dut2', 'DUT2')], default='licence1', max_length=20)),
                ('statut', models.CharField(choices=[('En Frequentation', 'En Fréquentation'), ('Ancien etudiant', 'Ancien étudiant')], default='En Frequentation', max_length=20)),
                ('role', models.CharField(default='etudiant', max_length=10)),
                ('mois_debut_annee_academique', models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=9)),
                ('annee_academique', models.CharField(default=None, max_length=9)),
                ('annee_frequentation_fin', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(default=None, max_length=254, unique=True)),
                ('genre', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], default='Homme', max_length=10)),
                ('mot_de_passe', models.CharField(default=None, max_length=255)),
                ('confirmer_mot_de_passe', models.CharField(default=None, max_length=255)),
                ('imagesprofiles', models.ImageField(default='../static/assets_dash/r.jpg', max_length=500, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Memoire',
            fields=[
                ('Id_mem', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('date_poste', models.DateField(default=datetime.date.today)),
                ('identite', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='EtudiantApp.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet_demande', models.CharField(choices=[('attestation_frequentation', 'Attestation de fréquentation'), ('attestation_reussite', 'Attestation de réussite'), ('releve', 'Relevé')], max_length=50)),
                ('session', models.CharField(choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4')], max_length=2)),
                ('filiere', models.CharField(choices=[('informatique', 'Informatique'), ('administration', 'Administration')], max_length=50)),
                ('cycle', models.CharField(choices=[('DUT', 'DUT'), ('LICENCE', 'Licence')], max_length=50)),
                ('annee_academique', models.CharField(max_length=10)),
                ('identite_concerne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EtudiantApp.etudiant')),
                ('identite_receptioniste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSSAPP.css')),
            ],
        ),
    ]
