# Generated by Django 4.2.7 on 2023-11-16 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EtudiantApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoire',
            name='co_auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='co_auteur', to='EtudiantApp.etudiant'),
        ),
        migrations.AlterField(
            model_name='memoire',
            name='identite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='auteur_principal', to='EtudiantApp.etudiant'),
        ),
    ]
