# Generated by Django 4.2.6 on 2023-10-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtudiantApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='cycle',
            field=models.CharField(choices=[('licence', 'Licence'), ('dut', 'DUT')], default='licence', max_length=20),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='filiere',
            field=models.CharField(choices=[('informatique', 'INFORMATIQUE'), ('administration', 'ADMINISTRATION')], default='informatique', max_length=20),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='niveaux',
            field=models.CharField(choices=[('licence1', 'LICENCE1'), ('licence2', 'LICENCE2'), ('licence3', 'LICENCE3'), ('dut1', 'DUT1'), ('dut2', 'DUT2')], default='licence1', max_length=20),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='civilite',
            field=models.CharField(choices=[('marié', 'Marié'), ('veuf(ve)', 'Veuf(ve)'), ('célibataire', 'Célibataire')], default='Célibataire', max_length=20),
        ),
    ]
