# Generated by Django 4.2.6 on 2023-10-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtudiantApp', '0002_etudiant_cycle_etudiant_filiere_etudiant_niveaux_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='civilite',
            field=models.CharField(choices=[('marié', 'MARIE'), ('veuf(ve)', 'VEUF(VE)'), ('célibataire', 'CELIBATAIRE')], default='Célibataire', max_length=20),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='cycle',
            field=models.CharField(choices=[('licence', 'LICENCE'), ('dut', 'DUT')], default='licence', max_length=20),
        ),
    ]
