# Generated by Django 4.2.7 on 2023-11-20 20:17

import EtudiantApp.data_models.memoire
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtudiantApp', '0002_memoire_co_auteur_alter_memoire_identite'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoire',
            name='document',
            field=models.FileField(default=1, upload_to='memoires/', validators=[EtudiantApp.data_models.memoire.validate_pdf_extension]),
            preserve_default=False,
        ),
    ]
