# Generated by Django 4.2.7 on 2023-12-30 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EtudiantApp', '0003_alter_etudiant_first_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='EtudiantApp.etudiant'),
        ),
    ]
