# Generated by Django 4.2.7 on 2023-12-30 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EtudiantApp', '0004_alter_demande_etudiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EtudiantApp.etudiant'),
        ),
    ]
