# Generated by Django 4.2.6 on 2023-10-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtudiantApp', '0004_etudiant_annee_academique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='annee_frequentation_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
