# Generated by Django 4.2.7 on 2023-11-20 23:13

import EtudiantApp.data_models.memoire
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtudiantApp', '0004_alter_memoire_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoire',
            name='document',
            field=models.FileField(max_length=500, upload_to='memoires', validators=[EtudiantApp.data_models.memoire.validate_pdf_extension]),
        ),
    ]
