# Generated by Django 4.2.7 on 2023-11-28 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtudiantApp', '0005_alter_memoire_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='Identification',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='annee_academique',
            field=models.CharField(choices=[('2023 - 2024', '2023 - 2024'), ('2024 - 2025', '2024 - 2025'), ('2025 - 2026', '2025 - 2026'), ('2026 - 2027', '2026 - 2027'), ('2027 - 2028', '2027 - 2028'), ('2028 - 2029', '2028 - 2029'), ('2029 - 2030', '2029 - 2030')], default='2023 - 2024', max_length=19),
        ),
    ]
