# Generated by Django 4.2.7 on 2024-01-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtudiantApp', '0005_alter_demande_etudiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='statut',
            field=models.CharField(choices=[('En Fréquentation', 'En Fréquentation'), ('Ancien étudiant', 'Ancien étudiant')], default='En Fréquentation', max_length=20),
        ),
    ]
