# Generated by Django 4.2.6 on 2023-10-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtudiantApp', '0005_alter_etudiant_annee_frequentation_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='role',
            field=models.CharField(default='etudiant', editable=False, max_length=10),
        ),
    ]
