# Generated by Django 4.2.6 on 2023-10-30 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EtudiantApp', '0006_etudiant_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='role',
        ),
    ]
