# Generated by Django 4.2.7 on 2023-11-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtudiantApp', '0006_etudiant_identification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memoire',
            name='co_auteur',
        ),
        migrations.AddField(
            model_name='memoire',
            name='matricule_identification_binome',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
