# Generated by Django 4.2.7 on 2024-01-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtudiantApp', '0006_alter_etudiant_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='etat',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Acceptée', 'Acceptée'), ('En cours de traitement', 'En cours de traitement'), ('Terminée', 'Terminée')], default='En attente', max_length=30),
        ),
    ]
