# Generated by Django 4.2.6 on 2023-10-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtudiantApp', '0007_remove_etudiant_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='role',
            field=models.CharField(default='etudiant', editable=False, max_length=10),
        ),
    ]
