# Generated by Django 4.2.7 on 2023-12-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtudiantApp', '0007_remove_memoire_co_auteur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='objet_demande',
            field=models.CharField(choices=[('attestation_frequentation', 'Attestation de fréquentation'), ('attestation_reussite', 'Attestation de réussite'), ('bulletin', 'Bulletin')], max_length=50),
        ),
    ]
