# Generated by Django 4.2.7 on 2023-12-02 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtudiantApp', '0008_alter_demande_objet_demande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='annee_academique',
            field=models.CharField(choices=[('2023 - 2024', '2023 - 2024'), ('2024 - 2025', '2024 - 2025'), ('2025 - 2026', '2025 - 2026'), ('2026 - 2027', '2026 - 2027'), ('2027 - 2028', '2027 - 2028'), ('2028 - 2029', '2028 - 2029'), ('2029 - 2030', '2029 - 2030')], max_length=50),
        ),
    ]
