# Generated by Django 4.2.6 on 2023-10-30 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EtudiantApp', '0008_etudiant_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etudiant',
            old_name='role',
            new_name='roles',
        ),
    ]
