# Generated by Django 4.2.7 on 2023-12-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtudiantApp', '0009_alter_demande_annee_academique'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demande',
            old_name='session',
            new_name='session_dut',
        ),
        migrations.AddField(
            model_name='demande',
            name='session_lic',
            field=models.CharField(choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4'), ('S5', 'S5'), ('S6', 'S6')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
