# Generated by Django 4.2.6 on 2023-10-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtudiantApp', '0009_rename_role_etudiant_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='roles',
            field=models.CharField(default='etudiant', max_length=10),
        ),
    ]
