# Generated by Django 4.2.7 on 2023-12-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtudiantApp', '0010_rename_session_demande_session_dut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoire',
            name='binome_notification_envoyee',
            field=models.BooleanField(default=False),
        ),
    ]
