# Generated by Django 4.2.6 on 2023-10-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtudiantApp', '0010_alter_etudiant_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='roles',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='role',
            field=models.CharField(default='etudiant', editable=False, max_length=10),
        ),
    ]
