# Generated by Django 4.2.7 on 2024-03-22 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtudiantApp', '0010_notification_destinataire_dir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='choix_semestre',
            field=models.CharField(choices=[('impair', 'Semestre impair'), ('pair', 'Semestre pair')], default=23032024, max_length=50),
            preserve_default=False,
        ),
    ]
