# Generated by Django 4.2.7 on 2024-03-23 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtudiantApp', '0011_demande_choix_semestre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='choix_semestre',
        ),
        migrations.AddField(
            model_name='demande',
            name='choix_session',
            field=models.CharField(choices=[('ordinaire', 'session ordinaire'), ('rattrapage', 'session  rattrapage')], default=23032024, max_length=50),
            preserve_default=False,
        ),
    ]
