# Generated by Django 4.2.6 on 2023-10-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtudiantApp', '0011_remove_etudiant_roles_etudiant_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='role',
            field=models.CharField(default='etudiant', max_length=10),
        ),
    ]
