# Generated by Django 4.2.7 on 2024-03-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtudiantApp', '0013_demande_niveau_dut_demande_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='choix_session',
            field=models.CharField(blank=True, choices=[('ordinaire', 'session ordinaire'), ('rattrapage', 'session  rattrapage')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='demande',
            name='niveau_dut_demande',
            field=models.CharField(blank=True, choices=[('dut1', 'DUT1'), ('dut2', 'DUT2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='demande',
            name='niveau_licence_demande',
            field=models.CharField(blank=True, choices=[('licence1', 'LICENCE1'), ('licence2', 'LICENCE2'), ('licence3', 'LICENCE3')], max_length=50, null=True),
        ),
    ]
