# Generated by Django 4.2.7 on 2023-12-09 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtudiantApp', '0014_rename_utilisateur_etudiant_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='role',
            field=models.CharField(choices=[('CSS', 'CSS'), ('Directeur', 'Directeur'), ('Etudiant', 'Etudiant')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
