# Generated by Django 4.2.7 on 2023-12-09 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtudiantApp', '0015_etudiant_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='confirmer_mot_de_passe',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='mot_de_passe',
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='genre',
            field=models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], default='Homme', max_length=20),
        ),
    ]
