# Generated by Django 4.2.7 on 2023-12-09 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EtudiantApp', '0016_remove_etudiant_confirmer_mot_de_passe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='prenom',
        ),
    ]
