# Generated by Django 4.2.7 on 2023-12-10 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CSSAPP', '0005_remove_css_nom_remove_css_prenom'),
        ('EtudiantApp', '0017_remove_etudiant_email_remove_etudiant_nom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demande',
            old_name='identite_concerne',
            new_name='etudiant',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='cycle',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='filiere',
        ),
        migrations.AlterField(
            model_name='demande',
            name='identite_receptioniste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CSSAPP.css'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='session_dut',
            field=models.CharField(blank=True, choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='demande',
            name='session_lic',
            field=models.CharField(blank=True, choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4'), ('S5', 'S5'), ('S6', 'S6')], max_length=2, null=True),
        ),
    ]
