# Generated by Django 4.2.7 on 2023-12-11 22:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EtudiantApp', '0018_rename_identite_concerne_demande_etudiant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='cycle',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demande',
            name='date_naiss',
            field=models.DateField(default=django.utils.timezone.now, max_length=50),
        ),
        migrations.AddField(
            model_name='demande',
            name='filiere',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demande',
            name='genre',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demande',
            name='telephone',
            field=models.CharField(default=1111111111111111111, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demande',
            name='etudiant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EtudiantApp.etudiant'),
        ),
    ]
