# Generated by Django 4.2.7 on 2023-12-11 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EtudiantApp', '0020_alter_demande_date_naiss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demande',
            old_name='date_naiss',
            new_name='date_nais',
        ),
    ]
