# Generated by Django 4.2.7 on 2023-12-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtudiantApp', '0021_rename_date_naiss_demande_date_nais'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='niveau',
            field=models.CharField(default=1111111111111111, max_length=10),
            preserve_default=False,
        ),
    ]
