# Generated by Django 4.2.7 on 2023-12-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtudiantApp', '0022_demande_niveau'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
    ]
