# Generated by Django 4.2.7 on 2023-12-14 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtudiantApp', '0024_remove_etudiant_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
    ]
