# Generated by Django 4.2.7 on 2023-12-17 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EtudiantApp', '0025_etudiant_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='expediteur',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notifications_expediteur', to='EtudiantApp.etudiant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='destinataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='notifications_destinataire', to='EtudiantApp.etudiant'),
        ),
    ]
