# Generated by Django 4.2.7 on 2023-12-17 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EtudiantApp', '0026_notification_expediteur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='expediteur',
        ),
    ]
