# Generated by Django 4.2.7 on 2023-12-17 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EtudiantApp', '0027_remove_notification_expediteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='expediteur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notifications_expediteur', to='EtudiantApp.etudiant'),
            preserve_default=False,
        ),
    ]
