# Generated by Django 4.2.7 on 2023-12-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtudiantApp', '0028_notification_expediteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_refused',
            field=models.BooleanField(default=False),
        ),
    ]
