# Generated by Django 4.2.7 on 2024-01-31 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Directeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_login', models.BooleanField(default=True)),
                ('telephone', models.CharField(max_length=255)),
                ('date_nais', models.DateField()),
                ('civilite', models.CharField(choices=[('MARIÉ', 'MARIÉ'), ('VEUF(VE)', 'VEUF(VE)'), ('Célibataire', 'Célibataire')], default='Célibataire', max_length=20)),
                ('genre', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], default='Homme', max_length=20)),
                ('imagesprofiles', models.ImageField(default='images/r.jpeg', max_length=500, upload_to='images/')),
                ('role', models.CharField(choices=[('CSS', 'CSS'), ('Directeur', 'Directeur'), ('Etudiant', 'Etudiant')], max_length=20)),
                ('matricule', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
