# Generated by Django 4.2.7 on 2024-01-31 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DCFISPACE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directeur',
            name='signature',
            field=models.ImageField(default='signature/sign_dir1.jpng', max_length=500, upload_to='signature/'),
        ),
    ]
