# Generated by Django 4.2.7 on 2024-02-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DCFISPACE', '0002_directeur_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directeur',
            name='signature',
            field=models.ImageField(default='signature/X000001_signature.jpng', max_length=500, upload_to='signatures/'),
        ),
    ]
