# Generated by Django 4.2.7 on 2023-11-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('date_nais', models.DateField()),
                ('civilite', models.CharField(choices=[('marié', 'MARIE'), ('veuf(ve)', 'VEUF(VE)'), ('célibataire', 'CELIBATAIRE')], default='Célibataire', max_length=20)),
                ('role', models.CharField(default='css', max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('genre', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=10)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('confirmer_mot_de_passe', models.CharField(max_length=255)),
                ('imagesprofiles', models.ImageField(max_length=500, upload_to='images/')),
            ],
        ),
    ]
