# Generated by Django 4.2.7 on 2023-12-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSSAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='css',
            name='first_login',
            field=models.BooleanField(default=False),
        ),
    ]
