# Generated by Django 4.2.7 on 2023-12-08 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CSSAPP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='css',
            name='role',
        ),
        migrations.AddField(
            model_name='css',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='css',
            name='civilite',
            field=models.CharField(choices=[('MARIÉ', 'MARIÉ'), ('VEUF(VE)', 'VEUF(VE)'), ('Célibataire', 'Célibataire')], default='Célibataire', max_length=20),
        ),
        migrations.AlterField(
            model_name='css',
            name='genre',
            field=models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], default='Homme', max_length=20),
        ),
        migrations.AlterField(
            model_name='css',
            name='imagesprofiles',
            field=models.ImageField(default='images/r.jpeg', max_length=500, upload_to='images/'),
        ),
    ]
