# Generated by Django 4.2.6 on 2023-10-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSSAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='css',
            name='role',
            field=models.CharField(default='css', editable=False, max_length=10),
        ),
    ]
