# Generated by Django 4.2.6 on 2023-10-30 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSSAPP', '0002_css_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='css',
            name='role',
        ),
    ]
