# Generated by Django 4.2.7 on 2023-12-09 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSSAPP', '0002_remove_css_role_css_user_alter_css_civilite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='css',
            name='role',
            field=models.CharField(choices=[('CSS', 'CSS'), ('Directeur', 'Directeur'), ('Etudiant', 'Etudiant')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
