# Generated by Django 4.2.7 on 2024-02-01 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EtudiantApp', '0009_demande_date_termine'),
        ('DCFISPACE', '0002_directeur_signature'),
        ('CSSAPP', '0003_alter_css_first_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_register', models.DateField(auto_now_add=True)),
                ('is_signed', models.BooleanField(default=False)),
                ('file', models.ImageField(max_length=500, upload_to='bulletins/')),
                ('css', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CSSAPP.css')),
                ('directeur', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DCFISPACE.directeur')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='EtudiantApp.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types_attestation', models.CharField(max_length=500)),
                ('date_register', models.DateField(auto_now_add=True)),
                ('is_signed', models.BooleanField(default=False)),
                ('file', models.ImageField(max_length=500, upload_to='attestations/')),
                ('css', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CSSAPP.css')),
                ('directeur', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DCFISPACE.directeur')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='EtudiantApp.etudiant')),
            ],
        ),
    ]
