# Generated by Django 4.2.6 on 2023-10-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSSAPP', '0003_remove_css_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='css',
            name='role',
            field=models.CharField(default='css', editable=False, max_length=10),
        ),
    ]
