# Generated by Django 4.2.7 on 2023-12-09 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSSAPP', '0003_css_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='css',
            name='confirmer_mot_de_passe',
        ),
        migrations.RemoveField(
            model_name='css',
            name='mot_de_passe',
        ),
    ]
