# Generated by Django 4.2.7 on 2023-12-09 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSSAPP', '0004_remove_css_confirmer_mot_de_passe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='css',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='css',
            name='prenom',
        ),
    ]
