# Generated by Django 4.2.7 on 2024-02-01 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSSAPP', '0004_bulletin_attestation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attestation',
            name='css',
        ),
        migrations.RemoveField(
            model_name='attestation',
            name='directeur',
        ),
        migrations.RemoveField(
            model_name='bulletin',
            name='css',
        ),
        migrations.RemoveField(
            model_name='bulletin',
            name='directeur',
        ),
    ]
