# Generated by Django 4.2.6 on 2023-10-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSSAPP', '0004_css_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='css',
            name='role',
            field=models.CharField(default='css', max_length=10),
        ),
    ]
