# Generated by Django 4.2.7 on 2024-02-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSSAPP', '0005_remove_attestation_css_remove_attestation_directeur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attestation',
            name='is_transfer_css',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attestation',
            name='is_transfer_directeur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attestation',
            name='is_transfer_etudiant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='is_transfer_css',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='is_transfer_directeur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='is_transfer_etudiant',
            field=models.BooleanField(default=False),
        ),
    ]
