# Generated by Django 4.2.7 on 2023-12-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSSAPP', '0006_remove_css_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='css',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
    ]
