# Generated by Django 4.2.7 on 2024-02-11 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DCFISPACE', '0003_alter_directeur_signature'),
        ('CSSAPP', '0006_attestation_is_transfer_css_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attestation',
            name='profile_directeur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='DCFISPACE.directeur'),
        ),
        migrations.AddField(
            model_name='attestation',
            name='profiles_css',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='CSSAPP.css'),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='profile_directeur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='DCFISPACE.directeur'),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='profiles_css',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='CSSAPP.css'),
        ),
    ]
