# Generated by Django 4.2.7 on 2023-12-14 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSSAPP', '0007_css_first_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='css',
            name='first_login',
        ),
    ]
