# Generated by Django 4.2.7 on 2024-02-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSSAPP', '0007_attestation_profile_directeur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attestation',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
