# Generated by Django 4.2.7 on 2023-12-14 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSSAPP', '0008_remove_css_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='css',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
    ]
