# Generated by Django 4.2.7 on 2024-04-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSSAPP', '0010_alter_archives_file_archives_bulletins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archives_bulletins',
            name='file',
            field=models.FileField(max_length=500, upload_to='archives_bulletins/'),
        ),
    ]
